# Generated by Django 5.0.6 on 2024-07-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbhs_app', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dept',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
